---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 3"  # minute (0 - 59)-hour (0 - 23)-day of the month (1 - 31)-month (1 - 12)-day of the week (0 - 6)

jobs:
  job1:
    runs-on: ubuntu-latest
    name: compile
    steps:
    - uses: actions/checkout@v2

    - name: Get nodejs version
      run: node -v
    - run: export TOTO=hola
      
  job2:
    runs-on: ubuntu-latestß
    name: test
    steps:
    - uses: actions/checkout@v2

    - name: Get nodejs version
      run: node -v
    - run: echo $TOTO
      
  job3:
    runs-on: ubuntu-latest
    name: deploy
    steps:
    - uses: actions/checkout@v2

    - name: Get nodejs version
      run: node -v
