---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 3"  # minute (0 - 59)-hour (0 - 23)-day of the month (1 - 31)-month (1 - 12)-day of the week (0 - 6)
env:
  NETWORK: localhost
  URL: ${{ secrets.URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy smart contract
    steps:
    - uses: actions/checkout@v2

    - name: Get nodejs version
      run: node -v

    - name: Install hardhat and dependencies
      run: npm install --save-dev @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers @nomiclabs/hardhat-etherscan ethers
    
    - name: Start a local Hardhat node
      run: npx hardhat node & sleep 10; npx hardhat --version
    
    - name: Compile smart contract
      run: |
        npx hardhat compile --network $NETWORK
        ls -la

    - name: Test smart contract
      run: |
         npx hardhat test --network $NETWORK

    - name: Deploy smart contract
      run: |
        npx hardhat run scripts/deploy.js --network $NETWORK




