---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 3"  # minute (0 - 59)-hour (0 - 23)-day of the month (1 - 31)-month (1 - 12)-day of the week (0 - 6)

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy smart contract
    strategy:
      max-parallel: 1
      matrix:
        network:
          - localhost
          - rinkeby
    env:
      NETWORK: ${{ matrix.network }}
      URL: ${{ secrets.URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      SCRIPT_PATH: scripts/deploy.js
      
    steps:
    - uses: actions/checkout@v2

    - name: Get nodejs version
      run: node -v

    - name: Install hardhat and dependencies
      run: npm install --no-fund --save-dev dotenv @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers @nomiclabs/hardhat-etherscan ethers
    
    - name: Start a local Hardhat node
      run: npx hardhat node & sleep 3; npx hardhat --version
      if: ${{ matrix.network == 'localhost' }}
    
    - name: Compile smart contract
      run: |
        npx hardhat compile --network $NETWORK
        ls -la

    - name: Test smart contract
      run: |
         npx hardhat test --network $NETWORK

    - name: Deploy smart contract
      run: |
        export CONTRACT_ADDRESS=$(npx hardhat run $SCRIPT_PATH --network $NETWORK)
        echo "Please find the smart contract address: ${CONTRACT_ADDRESS}"
        echo CONTRACT_ADDRESS=$CONTRACT_ADDRESS >> $GITHUB_ENV
        
    - name: Verify smart contract on Etherscan
      run: |
        npx hardhat verify $CONTRACT_ADDRESS --network $NETWORK 
      if: ${{ matrix.network == 'localhost' }}
        




