---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7 * * 3"  # minute (0 - 59)-hour (0 - 23)-day of the month (1 - 31)-month (1 - 12)-day of the week (0 - 6)

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Deploy smart contract
    strategy:
      max-parallel: 1
      matrix:
        network:
          - localhost
          - rinkeby

      
    steps:
    - uses: actions/checkout@v2

    - name: Get nodejs version
      run: |
        node -v
        env
        ls -la
      
    - name: create env file
      run: |
        touch .env
        echo $URL >> .env
        echo $PRIVATE_KEY >> .env
        echo $ETHERSCAN_KEY >> .env
        ls -la
      env:
        NETWORK: ${{ matrix.network }}
        URL: ${{ secrets.URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
        TEST: ${{ secrets.TEST }}
        
    - name: Install hardhat and dependencies
      run: npm install --no-fund --save-dev dotenv @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers @nomiclabs/hardhat-etherscan ethers
    
    - name: Start a local Hardhat node
      run: npx hardhat node & sleep 5; npx hardhat --version
    
    - name: Compile smart contract
      run: |
        npx hardhat compile --network $NETWORK
        ls -la
      env:
        NETWORK: ${{ matrix.network }}
        URL: ${{ secrets.URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
        TEST: ${{ secrets.TEST }}

    - name: Test smart contract
      run: |
         npx hardhat test --network $NETWORK
      env:
        NETWORK: ${{ matrix.network }}
        URL: ${{ secrets.URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
        TEST: ${{ secrets.TEST }}

    - name: Deploy smart contract
      run: |
        npx hardhat run scripts/deploy.js --network $NETWORK
      env:
        NETWORK: ${{ matrix.network }}
        URL: ${{ secrets.URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
        TEST: ${{ secrets.TEST }}



